version: "3.7"
services:
  heimdall-web:
    image: "ghcr.io/heimdall-security/heimdall-web-service:main"
    container_name: "heimdall-web"
    networks:
    - "proxy"
    restart: "always"
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.heimdall-web.entrypoints=http"
    - "traefik.http.routers.heimdall-web.rule=Host(`dev.web.mayanksoni.tech`)&&PathPrefix(`/web`)"
    - "traefik.http.middlewares.heimdall-web-https-redirect.redirectscheme.scheme=https"
    - "traefik.http.routers.heimdall-web.middlewares=heimdall-web-https-redirect"
    - "traefik.http.routers.heimdall-web-websecure.entrypoints=https"
    - "traefik.http.routers.heimdall-web-websecure.rule=Host(`dev.web.mayanksoni.tech`)&&PathPrefix(`/web`)"
    - "traefik.http.routers.heimdall-web-websecure.tls=true"
    - "traefik.http.routers.heimdall-web-websecure.service=heimdall-web"
    - "traefik.http.services.heimdall-web.loadbalancer.server.port=80"
    - "traefik.docker.network=proxy"
  heimdall-identity-management:
    image: "ghcr.io/heimdall-security/heimdall-idm:master"
    container_name: "heimdall-identity-management"
    networks:
    - "proxy"
    - "internal"
    restart: "always"
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.heimdall-identity-management.entrypoints=http"
    - "traefik.http.routers.heimdall-identity-management.rule=Host(`dev.web.mayanksoni.tech`)&&PathPrefix(`/api/idm`)"
    - "traefik.http.middlewares.heimdall-identity-management-https-redirect.redirectscheme.scheme=https"
    - "traefik.http.routers.heimdall-identity-management.middlewares=heimdall-identity-management-https-redirect"
    - "traefik.http.routers.heimdall-identity-management-websecure.entrypoints=https"
    - "traefik.http.routers.heimdall-identity-management-websecure.rule=Host(`dev.web.mayanksoni.tech`)&&PathPrefix(`/api/idm`)"
    - "traefik.http.routers.heimdall-identity-management-websecure.tls=true"
    - "traefik.http.routers.heimdall-identity-management-websecure.service=heimdall-identity-management"
    - "traefik.http.services.heimdall-identity-management.loadbalancer.server.port=8080"
    - "traefik.docker.network=proxy"
  heimdall-tenant-service:
    image: "ghcr.io/heimdall-security/heimdall-tenant-service:main"
    container_name: "heimdall-tenant-service"
    networks:
    - "proxy"
    restart: "always"
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.heimdall-tenant-service.entrypoints=http"
    - "traefik.http.routers.heimdall-tenant-service.rule=Host(`dev.web.mayanksoni.tech`)&&PathPrefix(`/api/tenant`)"
    - "traefik.http.middlewares.heimdall-tenant-service-https-redirect.redirectscheme.scheme=https"
    - "traefik.http.routers.heimdall-tenant-service.middlewares=heimdall-tenant-service-https-redirect"
    - "traefik.http.routers.heimdall-tenant-service-websecure.entrypoints=https"
    - "traefik.http.routers.heimdall-tenant-service-websecure.rule=Host(`dev.web.mayanksoni.tech`)&&PathPrefix(`/api/tenant`)"
    - "traefik.http.routers.heimdall-tenant-service-websecure.tls=true"
    - "traefik.http.routers.heimdall-tenant-service-websecure.service=heimdall-tenant-service"
    - "traefik.http.services.heimdall-tenant-service.loadbalancer.server.port=8080"
    - "traefik.docker.network=proxy"
networks:
  proxy:
    external: true
  internal: